# Forward and backward error

$$
\begin{align*}
& \Delta x \approx \frac{f(x + \Delta x) - f(x)}{\Delta x} = \Delta y \\

& |\frac{\frac{\Delta y}{y}}{\frac{\Delta x}{x}}| = \frac{\frac{\Delta xf'(x)}{y}}{\frac{\Delta x}{x}} = \frac{x \Delta x f'(x)}{\Delta x y} \\
\end{align*}
$$

## Condition number

$$
\begin{align*}

& C_f = \frac{x f'(x)}{f(x)} \\

\end{align*}
$$

# Gaussian emilimiation

In [20]:
import numpy as np

A = np.array([[1, 2, 2], [4, 4, 2], [4, 6, 4]])

In [21]:
def forward_elimination(A, p):
    pivot = A[p, p]
    M = np.eye(len(A))
    for row_index in range(p + 1, len(A)):
        M[row_index, p] = -A[row_index, p] / pivot
    return M

In [22]:
forward_elimination(A, 0)

array([[ 1.,  0.,  0.],
       [-4.,  1.,  0.],
       [-4.,  0.,  1.]])

In [23]:
M1 = forward_elimination(A, 0)

In [24]:
M2 = forward_elimination(np.dot(M1, A), 1)

In [25]:
np.dot(M2, np.dot(M1, A))

array([[ 1.,  2.,  2.],
       [ 0., -4., -6.],
       [ 0.,  0., -1.]])

In [26]:
def transform(A):
    pass

In [28]:
transform(A)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])