# Lecture 1

In [2]:
import numpy as np

In [3]:
A = np.array([[1, 2, 3], [3, 2, 1], [2, 3, 1]])

In [5]:
L, S = np.linalg.eig(A)

In [7]:
L

array([ 6.+0.j, -1.+1.j, -1.-1.j])

In [8]:
S

array([[ 0.57735027+0.j        ,  0.65790259+0.j        ,
         0.65790259-0.j        ],
       [ 0.57735027+0.j        , -0.52178481-0.31760815j,
        -0.52178481+0.31760815j],
       [ 0.57735027+0.j        , -0.09074519+0.43103963j,
        -0.09074519-0.43103963j]])

In [9]:
D = np.diag(L)

In [10]:
np.dot(np.dot(S, D), np.linalg.inv(S))

array([[1.-2.71572861e-16j, 2.+3.61191275e-17j, 3.+4.64377365e-18j],
       [3.-9.30214692e-17j, 2.+1.46766551e-17j, 1.-1.96420515e-17j],
       [2.-1.15408428e-16j, 3.+4.92852301e-18j, 1.-1.79980432e-17j]])

# Applied

## Forward and backward error

forward error is an error in output

backward error is an error in input


# Question 1

$$
f(x) = x^2 \\

condition number = |\frac{xf'(x)}{f(x)}|
$$

In [4]:
# Question 3 - function to perform LU decomposition

def lu_decomposition(A):
    n = len(A)
    L = np.zeros((n,n))
    U = np.zeros((n,n))
    for i in range(n):
        L[i,i] = 1
        for j in range(i,n):
            U[i,j] = A[i,j] - np.dot(L[i,:i],U[:i,j])
        for j in range(i+1,n):
            L[j,i] = (A[j,i] - np.dot(L[j,:i],U[:i,i]))/U[i,i]
    return L, U

A = np.array([[1, 2, 3], [3, 2, 1], [2, 3, 1]])
L, U = lu_decomposition(A)
print(L)
print(U)
np.dot(L,U)

[[1.   0.   0.  ]
 [3.   1.   0.  ]
 [2.   0.25 1.  ]]
[[ 1.  2.  3.]
 [ 0. -4. -8.]
 [ 0.  0. -3.]]


array([[1., 2., 3.],
       [3., 2., 1.],
       [2., 3., 1.]])

In [5]:
def LU(A):
    n = len(A)
    L = np.eye(n)
    U = A.copy()
    for i in range(n):
        for j in range(i+1,n):
            L[j,i] = U[j,i]/U[i,i]
            U[j,i:] = U[j,i:] - L[j,i]*U[i,i:]
    return L, U

A = np.array([[1, 2, 3], [3, 2, 1], [2, 3, 1]])
L, U = LU(A)
print(L)
print(U)
np.dot(L,U)

[[1.   0.   0.  ]
 [3.   1.   0.  ]
 [2.   0.25 1.  ]]
[[ 1  2  3]
 [ 0 -4 -8]
 [ 0  0 -3]]


array([[1., 2., 3.],
       [3., 2., 1.],
       [2., 3., 1.]])

# week 3 Lecture 2



A = np.array([])

In [10]:
A = np.array([[1, 2, 3], [3, 2, 1], [2, 3, 1]])
np.linalg.eig(A)

EigResult(eigenvalues=array([ 6.+0.j, -1.+1.j, -1.-1.j]), eigenvectors=array([[ 0.57735027+0.j        ,  0.65790259+0.j        ,
         0.65790259-0.j        ],
       [ 0.57735027+0.j        , -0.52178481-0.31760815j,
        -0.52178481+0.31760815j],
       [ 0.57735027+0.j        , -0.09074519+0.43103963j,
        -0.09074519-0.43103963j]]))

In [15]:
x = np.array([1, 2, 3])
for i in range(20):
    print(x)
    x = np.dot(A, x)
    factor = np.linalg.norm(x)
    x = x/factor

[1 2 3]
[0.68558295 0.48970211 0.53867232]
[0.55489516 0.60458726 0.57145919]
[0.57825792 0.57275071 0.58101153]
[0.5782684  0.57734978 0.57643117]
[0.576993   0.57760536 0.57745227]
[0.5774183  0.57726522 0.57736728]
[0.57734743 0.57736444 0.57733893]
[0.57734743 0.57735027 0.5773531 ]
[0.57735137 0.57734948 0.57734995]
[0.57735006 0.57735053 0.57735022]
[0.57735028 0.57735023 0.5773503 ]
[0.57735028 0.57735027 0.57735026]
[0.57735027 0.57735027 0.57735027]
[0.57735027 0.57735027 0.57735027]
[0.57735027 0.57735027 0.57735027]
[0.57735027 0.57735027 0.57735027]
[0.57735027 0.57735027 0.57735027]
[0.57735027 0.57735027 0.57735027]
[0.57735027 0.57735027 0.57735027]


# Jacobi Iteration

In [19]:
A = np.array([[10, -1, 2, 0], [-1, 11, -1, 3], [2, -1, 10, -1], [0, 3, -1, 8]])
b = np.array([6, 25, -11, 15])
np.linalg.solve(A, b)

array([ 1.,  2., -1.,  1.])

In [21]:
L = np.zeros_like(A)
D = np.zeros_like(A)
R = np.zeros_like(A)

In [23]:
for i in range(len(A)):
    for j in range(len(A)):
        if i == j:
            D[i,j] = A[i,j]
        elif j > i:
            # if columns are greater than rows, then it is upper triangular
            R[i,j] = A[i,j]
        else:
            # if columns are less than rows, then it is lower triangular
            L[i,j] = A[i,j]

In [29]:
D_inv = np.linalg.inv(D)

In [32]:
x = np.array([1, 1, 1, 1])
for _ in range(10):
    x = np.dot(D_inv, b) + np.dot(np.dot(-D_inv, L+R), x)
    print(x)

[ 0.5         2.18181818 -1.1         1.625     ]
[ 1.03818182  1.775      -0.81931818  0.91931818]
[ 0.94136364  2.04190083 -1.03820455  1.10696023]
[ 1.01183099  1.96202531 -0.97338662  0.97951162]
[ 0.99087986  2.00908268 -1.00821251  1.01756718]
[ 1.00255077  1.99363326 -0.99551098  0.99556743]
[ 0.99846552  2.00184886 -1.00159009  1.00294866]
[ 1.0005029   1.99891177 -0.99921335  0.99910792]
[ 0.99973385  2.00036053 -1.00029861  1.00050642]
[ 1.00009578  1.99981054 -0.99986008  0.99982748]


In [ ]:
def jacobi(A, b, num_iterations):
    n = len(A)
    for i in range(num_iterations):
        for j in range(0, n):
            